// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh5cs7atk_d47cLnpVbNy7V0OfjcUmgJs',
    appId: '1:637809558409:web:360522a982e98a32ce9758',
    messagingSenderId: '637809558409',
    projectId: 'connection1-16bff',
    authDomain: 'connection1-16bff.firebaseapp.com',
    storageBucket: 'connection1-16bff.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPs94rpwXX8U_LCH4IY0Pws7s4ZVBGaeE',
    appId: '1:637809558409:android:19fe34401183de47ce9758',
    messagingSenderId: '637809558409',
    projectId: 'connection1-16bff',
    storageBucket: 'connection1-16bff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBliEpB8_K3bFS0jL5SfZdeeVqy3hhUQJ4',
    appId: '1:637809558409:ios:a6d3f5307b26f31ace9758',
    messagingSenderId: '637809558409',
    projectId: 'connection1-16bff',
    storageBucket: 'connection1-16bff.appspot.com',
    iosClientId: '637809558409-bu0o977tkhid52es4kvkurl69pb3n3te.apps.googleusercontent.com',
    iosBundleId: 'com.example.cleverDb',
  );
}
